/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mophong_atm;

import mophong_atm.processData.Customer;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author at01
 */
public class ChuyenKhoan extends javax.swing.JFrame {
    static ArrayList<Customer> list;
     SignIn signin;
    /**
     * Creates new form ChuyenKhoan
     */
    public ChuyenKhoan() {
        initComponents();
        this.list=signin.list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtChuyenSoTien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSTKChuyen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chuyển Khoản");

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        btnOK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        btnOK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnOKKeyPressed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        btnCancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelKeyPressed(evt);
            }
        });

        txtChuyenSoTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChuyenSoTienActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Chuyển số tiền ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chuyển tiền tới số TK");

        txtSTKChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSTKChuyenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSTKChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtChuyenSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSTKChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtChuyenSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        int d=0;
        for(int i=0;i<list.size();i++){
            if(list.get(i).pass.equals(signin.password))
            {
                d=i;
            }
        }
        //int _tk=Integer.parseInt(jTextField2.getText());
        //double _tk =0;
        //checkFormat: Kiem tra so tien can chuyen la 1 so
//        boolean checkFormat=true;
//        try {
//             _tk=Double.parseDouble(jTextField2.getText());
//        } catch (NumberFormatException e) {
//            //JOptionPane.showMessageDialog(this, e.getMessage());
//            checkFormat=false;
//            setjTextField1(jTextField2);
//        }
//        
        //String acount=jTextField1.getText();
        //JOptionPane.showMessageDialog(this, "Test: "+list.get(d).name);
        //Check1: Kiem tra tai khoan nguoi nhan trung TK nguoi gui
        //boolean check1=jTextField1.getText().equals(list.get(d).so_tk);
        if(txtSTKChuyen.getText().length()!=0){
            //JOptionPane.showMessageDialog(this, "OK");
            //Check: Kiem tra nguoi nhan co trong DataBase ko?
            boolean check=false;
            for(int i=0;i<list.size();i++){
                if(list.get(i).so_tk.equals(txtSTKChuyen.getText()))
                    check=true;
            }
            //Check jTextFiled2 khac Null
            if(txtChuyenSoTien.getText().length()!=0){
                //Check nguoi nhan co trong DataBase
                if(check){
                    //Check trung tai khoan nguoi gui
                    if(!txtSTKChuyen.getText().equals(list.get(d).so_tk)){
                        //JOptionPane.showMessageDialog(this, "OK");
                        //checkFormat: Kiem tra so tien can chuyen la 1 so
                        double _tk =0;
                        boolean checkFormat=true;
                        try {
                             _tk=Double.parseDouble(txtChuyenSoTien.getText());
                        } catch (NumberFormatException e) {
                            //JOptionPane.showMessageDialog(this, e.getMessage());
                            checkFormat=false;
                            //setjTextField1(jTextField2);
                        }
                        //Check so tien phai la so
                        if(checkFormat){
                            /////////////////////////////////////
                            if(_tk>0){
                                if(list.get(d).tk-50<_tk){
                                        JOptionPane.showMessageDialog(this, "Tài khoản không đủ để thực hiện giao dịch");
                                        settxtSTKChuyen(txtSTKChuyen);
                                }
                                else{
                                    list.get(d).tk-=_tk;
                                    processData prD=new processData();
                                    File f=new File("dataATM.txt");
                                    try {            
                                        prD.writeListToFile(list, f);
                                    } catch (FileNotFoundException ex) {
                                        Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                                    } catch (IOException ex) {
                                        Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                    JOptionPane.showMessageDialog(this, "Chuyển khoản thành công");
                                    this.dispose();
                                    //new Desktop().setVisible(true);
                                }
                            }
                            else{
                                 JOptionPane.showMessageDialog(this, "Số tiền cần chuyển phải lớn hơn 0");
                                 settxtChuyenSoTien(txtChuyenSoTien);
                            }
                            ////////////////////////////////////
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Số tiền bạn nhập không đúng");
                            //setjTextField1(jTextField1);//
                            settxtChuyenSoTien(txtChuyenSoTien);
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Không thể chuyển khoản cho chính bạn");
                        settxtSTKChuyen(txtSTKChuyen);
                    }

                }
                else{
                    JOptionPane.showMessageDialog(this, "Tài khoản người nhận không đúng");
                    settxtSTKChuyen(txtSTKChuyen);
                }

            }
            if(txtChuyenSoTien.getText().length()==0){
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập số tiền cần chuyển");
                settxtChuyenSoTien(txtChuyenSoTien);
            }
        }
        if(txtSTKChuyen.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tài khoản");
            settxtSTKChuyen(txtSTKChuyen);
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //new Desktop().setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtSTKChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSTKChuyenActionPerformed
        // TODO add your handling code here:
        btnOKActionPerformed(evt);
    }//GEN-LAST:event_txtSTKChuyenActionPerformed

    private void txtChuyenSoTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChuyenSoTienActionPerformed
        // TODO add your handling code here:
        btnOKActionPerformed(evt);
    }//GEN-LAST:event_txtChuyenSoTienActionPerformed

    private void btnOKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnOKKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnOKActionPerformed(null);
        }
    }//GEN-LAST:event_btnOKKeyPressed

    private void btnCancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnCancelActionPerformed(null);
        }
    }//GEN-LAST:event_btnCancelKeyPressed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChuyenKhoan().setVisible(true);
            }
        });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtChuyenSoTien;
    private javax.swing.JTextField txtSTKChuyen;
    // End of variables declaration//GEN-END:variables

    public void settxtSTKChuyen(JTextField txtSTKChuyen) {
        this.txtSTKChuyen = txtSTKChuyen;
    }

    public void settxtChuyenSoTien(JTextField txtChuyenSoTien) {
        this.txtChuyenSoTien = txtChuyenSoTien;
    }

}
