/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SingIn.java
 *
 * Created on Jan 5, 2013, 5:51:21 PM
 */

//jPanel1 = new javax.swing.JPanel(){
//    ImageIcon icon = new ImageIcon("DSC_4104.JPG");
//    public void paintComponent(Graphics g){
//        Dimension d = getSize();
//        g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
//        setOpaque(false);
//        super.paintComponent(g);
//    }
//};
package mophong_atm;

import mophong_atm.processData.Customer;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
//import atm_v1.Sound_cdjv;
import java.awt.Event;
import java.awt.event.KeyEvent;
import javax.swing.JPasswordField;

/**
 *
 * @author NhuongTT2
 */
public class SignIn extends javax.swing.JFrame {
    static ArrayList<Customer> list;
    private Component frame;
    static String user="";
    static String password="";
    
    /** Creates new form SingIn */
    public SignIn() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDangnhap = new javax.swing.JButton();
        btnThemTK = new javax.swing.JButton();
        txtMapin = new javax.swing.JPasswordField();
        txtSoTK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập");
        setBackground(new java.awt.Color(51, 0, 255));

        panel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("ABC-Bank kính chào quý khách");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nhập mã PIN");

        btnDangnhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDangnhap.setText("Đăng nhập");
        btnDangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangnhapActionPerformed(evt);
            }
        });
        btnDangnhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDangnhapKeyPressed(evt);
            }
        });

        btnThemTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThemTK.setText("Thêm TK");
        btnThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTKActionPerformed(evt);
            }
        });
        btnThemTK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnThemTKKeyPressed(evt);
            }
        });

        txtMapin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMapinActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Card Number");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoTK, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMapin)
                                .addGroup(panel1Layout.createSequentialGroup()
                                    .addComponent(btnDangnhap)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                    .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMapin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangnhap)
                    .addComponent(btnThemTK))
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangnhapActionPerformed
        // TODO add your handling code here:
        user=txtSoTK.getText();
        password=txtMapin.getText();
        processData prD=new processData();
        try {
            this.list=prD.result();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        //JOptionPane.showMessageDialog(frame,user+" "+password);
        boolean check=false;
        for(int i=0;i<list.size();i++){
            if(list.get(i).pass.equals(txtMapin.getText())&& list.get(i).so_tk.equals(txtSoTK.getText())){
                
                this.dispose();
                new GiaoDienChinh().setVisible(true);
                //sound.start();
                check=true;
            }
        }
        if(txtMapin.getText().length()!=0 && txtSoTK.getText().length()!=0){
            if(check==false){
                JOptionPane.showMessageDialog(frame, "Sai tài khoản hoặc mã PIN");
                settxtMapin(txtMapin);
                settxtSoTK(txtSoTK);
            }
        }
        else{
           JOptionPane.showMessageDialog(frame, "Vui lòng nhập đầy đủ");
           settxtMapin(txtMapin);
           settxtSoTK(txtSoTK);
        }
    }//GEN-LAST:event_btnDangnhapActionPerformed

    private void btnThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTKActionPerformed
        // TODO add your handling code here:
        //jButton2ActionPerformed(evt);
        this.dispose();
        new AddAcount().setVisible(true);
        
    }//GEN-LAST:event_btnThemTKActionPerformed

    private void btnDangnhapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDangnhapKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
              btnDangnhapActionPerformed(null);
        }
    }//GEN-LAST:event_btnDangnhapKeyPressed

    private void btnThemTKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnThemTKKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnThemTKActionPerformed(null);
        }
    }//GEN-LAST:event_btnThemTKKeyPressed

    private void txtMapinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMapinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMapinActionPerformed

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SingIn().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangnhap;
    private javax.swing.JButton btnThemTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Panel panel1;
    private javax.swing.JPasswordField txtMapin;
    private javax.swing.JTextField txtSoTK;
    // End of variables declaration//GEN-END:variables



    public void settxtMapin(JPasswordField txtMapin) {
        this.txtMapin = txtMapin;
    }

    public JPasswordField gettxtMapin() {
        return txtMapin;
    }
    public void settxtSoTK(JTextField txtSoTK) {
        this.txtSoTK = txtSoTK;
    }

    public JTextField gettxtSoTK() {
        return txtSoTK;
    }
}
